# Required
baseURL = "https://dotfiles.yingw787.com"
languageCode = "en-us"
title = "Dotfiles"
theme = "carrd50"

# Optional
googleAnalytics = ""

[params]
    # Required #
    author = "Ying Wang"
    email = "me@yingw787.com"
    description = "Website to host my dotfiles."
    copyrightYear = "Forever"
    favicon = "img/favicon.png"

    # Optional #
    font = "Space Mono" # Available fonts include: ["Space Mono"].
    titleImage = "img/image01.png"
    titleTextColor = "#93a1a1"
    bodyTextColor = "#93a1a1"
    backgroundColor = "#002b36"

    formInputColor = "#666666"
    formBackgroundColor = "#93a1a1"
    formSelectedColor = "#1ABC9C"

    buttonColor = "#93a1a1"
    buttonBackgroundColor = "#3BACFF"

    footerTextColor = "#93a1a1"

    mailchimpURL = ""
    mailchimpBotDecoyLink = ""
